Description: 'Mobile Live Streaming AWS'
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Description: Project name
    Type: String
    Default: mobilelive

Globals:
  Function:
    Timeout: 180
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
# ---------- IAM ROLES FOR SERVIES ---------
  MediaLiveRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - "medialive.amazonaws.com"
              Action:
                - sts:AssumeRole
        ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  # Not needed
  # MediaPackageRole:
  #     Type: AWS::IAM::Role
  #     Properties:
  #       AssumeRolePolicyDocument:
  #         Version: 2012-10-17
  #         Statement:
  #           -
  #             Effect: Allow
  #             Principal:
  #               Service:
  #                 - "mediapackage.amazonaws.com"
  #             Action:
  #               - sts:AssumeRole
  #       ManagedPolicyArns:
  #       - 'arn:aws:iam::aws:policy/AdministratorAccess'
  #       # Policies:
  #       # CdnIdentifierSecret (string) -- [REQUIRED] The Amazon Resource Name (ARN) for the secret in Secrets Manager that your Content Distribution Network (CDN) uses for authorization to access your endpoint.
  #       # SecretsRoleArn (string) -- [REQUIRED] The Amazon Resource Name (ARN) for the IAM role that allows MediaPackage to communicate with AWS Secrets Manager.
  # TODO: SCOPE ROLE
  LiveStreamLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ProjectName}-LiveStreamLambdaRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  LiveStreamArchiveBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
    #   BucketName: !Sub '${ProjectName}-livestream-archive'

  LiveStreamArchiveOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "web-access-${LiveStreamArchiveBucket}"
  LiveStreamArchiveBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LiveStreamArchiveBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Join ['',['arn:aws:s3:::',!Ref LiveStreamArchiveBucket,'/*']]
            Principal:
              CanonicalUser: !GetAtt LiveStreamArchiveOriginAccessIdentity.S3CanonicalUserId
  WebCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior: # S3 origin is default
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods: # Cache get requests only
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 300
          MaxTTL: 300
          ForwardedValues:
            Headers:
              - Origin
            QueryString: true
          TargetOriginId: webstatic
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          # Alternative behavior for the API gateway
          - AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            CachedMethods: # Cache get requests only
            - GET
            - HEAD
            - OPTIONS
            Compress: false
            DefaultTTL: 300
            MaxTTL: 300
            ForwardedValues:
              Cookies:
                Forward: all
              Headers: # Need to whitelist all headers that API gateway requires:
                - Accept
                - Referer
                - Athorization
                - Origin
                - Content-Type
              QueryString: true
            PathPattern: "/vod/*"
            TargetOriginId: webstatic
            ViewerProtocolPolicy: https-only
          # Alternative behavior for the API gateway
          - AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods: # Cache get requests only
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            DefaultTTL: 0
            MaxTTL: 0
            ForwardedValues:
              Cookies:
                Forward: all
              Headers: # Need to whitelist all headers that API gateway requires:
                - Accept
                - Referer
                - Athorization
                - Content-Type
              QueryString: true
            PathPattern: "/Prod/*"
            TargetOriginId: api
            ViewerProtocolPolicy: https-only
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          -
            # Note: DO NOT use !GetAtt WebBucket.DomainName for DomainName
            # https://stackoverflow.com/q/38735306
            #DomainName: !GetAtt WebBucket.DomainName
            DomainName: !Sub ${LiveStreamArchiveBucket}.s3.amazonaws.com
            Id: webstatic
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${LiveStreamArchiveOriginAccessIdentity}
          -
            DomainName: !Join ['',[!Ref ServerlessRestApi,'.execute-api.',!Ref 'AWS::Region','.amazonaws.com']]
            Id: api
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        PriceClass: PriceClass_200
  MediaLiveSecurityGroup:
    Type: AWS::MediaLive::InputSecurityGroup
    Properties:
      WhitelistRules:
        - Cidr: '0.0.0.0/0'

# ---------- DYNAMODB TABLES DEFINITIONS ---------
  TableChannel:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${ProjectName}-Channel'
      AttributeDefinitions:
        - AttributeName: ChannelId
          AttributeType: S
      KeySchema:
        - AttributeName: ChannelId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  TableVoD:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${ProjectName}-VoD'
      AttributeDefinitions:
        - AttributeName: VoDID
          AttributeType: S
      KeySchema:
        - AttributeName: VoDID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

# ---------- SNS notification --------
  ChannelReadySNS:
    Type: AWS::SNS::Topic

# ---------- Lambda Function ---------
  FunctionAddChannel:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${ProjectName}-FunctionAddChannel'
      Description: GFunctionAddChannel
      Handler: addChannel.lambda_handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt LiveStreamLambdaRole.Arn
      Timeout: 300
      Environment:
        Variables:
          medialive_sg: !Ref MediaLiveSecurityGroup #medialive_sg id
          archive_s3 : !Ref LiveStreamArchiveBucket #archive_s3 bucketname
          medialive_role_arn : !GetAtt MediaLiveRole.Arn #medialive_role_arn role arn
          ddb_channel : !Ref TableChannel
      CodeUri: ./lambda/api/addChannel/
      Events:
        APIgateway:
          Type: Api
          Properties:
            Path: /channel/addChannel
            Method: post
  FunctionListChannel:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${ProjectName}-FunctionListChannel'
      Description: FunctionListChannel
      Handler: listChannel.lambda_handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt LiveStreamLambdaRole.Arn
      Timeout: 300
      Environment:
        Variables:
          ddb_channel : !Ref TableChannel
      CodeUri: ./lambda/api/listChannel/
      Events:
        APIgateway:
          Type: Api
          Properties:
            Path: /channel
            Method: get
  FunctionListVoD:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${ProjectName}-FunctionListVoD'
      Description: FunctionListVoD
      Handler: listVoD.lambda_handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt LiveStreamLambdaRole.Arn
      Timeout: 300
      Environment:
        Variables:
          ddb_channel : !Ref TableVoD
      CodeUri: ./lambda/api/listVoD/
      Events:
        APIgateway:
          Type: Api
          Properties:
            Path: /vod
            Method: get
  FunctionStreamStart:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${ProjectName}-FunctionStreamStart'
      Description: FunctionStreamStart
      Handler: streamStart.lambda_handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt LiveStreamLambdaRole.Arn
      Timeout: 300
      Environment:
        Variables:
          ddb_channel : !Ref TableChannel
      CodeUri: ./lambda/api/streamStart/
      Events:
        APIgateway:
          Type: Api
          Properties:
            Path: /channel/startChannel
            Method: post
  FunctionStreamStop:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${ProjectName}-FunctionStreamStop'
      Description: FunctionStreamStop
      Handler: streamStop.lambda_handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt LiveStreamLambdaRole.Arn
      Timeout: 300
      Environment:
        Variables:
          ddb_channel : !Ref TableChannel
      CodeUri: ./lambda/api/streamStop/
      Events:
        APIgateway:
          Type: Api
          Properties:
            Path: /channel/stopChannel
            Method: post
  FunctionOnChannelStateChange:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${ProjectName}-FunctionOnChannelStateChange'
      Description: OnChannelStateChange
      Handler: onChannelStateChange.lambda_handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt LiveStreamLambdaRole.Arn
      Timeout: 300
      Environment:
        Variables:
          ddb_channel : !Ref TableChannel
          ddb_vod : !Ref TableVoD
          snstopic : !Ref ChannelReadySNS
          archive_s3 : !Ref LiveStreamArchiveBucket
          vod_s3key : 'vod'
          CloudFrontVoDURL : !GetAtt WebCDN.DomainName
      CodeUri: ./lambda/event/onChannelStateChange/
      Events:
        CWEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.medialive
              detail-type:
              - MediaLive Channel State Change
              detail:
                state:
                  - STOPPED
                  - RUNNING

# Outputs: